var THEME_JSON = {
  name: "Modern",
  sprites: [
    {
      type: "Texture",
      name: "default",
      file: "dirt.jpg",
    },
    {
      type: "BikerPart",
      name: "PlayerBikerBody",
      file: "PlayerBikerBody.png",
    },
    {
      type: "BikerPart",
      name: "PlayerBikerFront",
      file: "playerfront.png",
    },
    {
      type: "BikerPart",
      name: "PlayerBikerRear",
      file: "playerrear.png",
    },
    {
      type: "BikerPart",
      name: "PlayerBikerWheel",
      file: "PlayerBikerWheel.png",
    },
    {
      type: "BikerPart",
      name: "PlayerLowerArm",
      file: "PlayerLowerArm.png",
    },
    {
      type: "BikerPart",
      name: "PlayerLowerLeg",
      file: "PlayerLowerLeg.png",
    },
    {
      type: "BikerPart",
      name: "PlayerTorso",
      file: "PlayerTorso.png",
    },
    {
      type: "BikerPart",
      name: "PlayerUpperArm",
      file: "PlayerUpperArm.png",
    },
    {
      type: "BikerPart",
      name: "PlayerUpperLeg",
      file: "PlayerUpperLeg.png",
    },
    {
      type: "BikerPart",
      name: "GhostTorso",
      file: "ghosttorso.png",
    },
    {
      type: "BikerPart",
      name: "GhostBikerBody",
      file: "ghostbikerbody.png",
    },
    {
      type: "BikerPart",
      name: "GhostBikerFront",
      file: "ghostbikerfront.png",
    },
    {
      type: "BikerPart",
      name: "GhostBikerRear",
      file: "ghostrear.png",
    },
    {
      type: "BikerPart",
      name: "GhostBikerWheel",
      file: "ghostbikerwheel.png",
    },
    {
      type: "BikerPart",
      name: "GhostLowerArm",
      file: "ghostlowerarm.png",
    },
    {
      type: "BikerPart",
      name: "GhostLowerLeg",
      file: "ghostlowerleg.png",
    },
    {
      type: "BikerPart",
      name: "GhostTorso",
      file: "ghosttorso.png",
    },
    {
      type: "BikerPart",
      name: "GhostUpperArm",
      file: "ghostupperarm.png",
    },
    {
      type: "BikerPart",
      name: "GhostUpperLeg",
      file: "ghostupperleg.png",
    },
    {
      type: "EdgeEffect",
      name: "darken",
      file: "darken.png",
      scale: "0.05",
      depth: "0.05",
    },
    {
      type: "Entity",
      name: "Finish",
      fileBase: "covid_cure_",
      fileExtension: "png",
      delay: "0.05",
      frames: 1,
    },
    {
      type: "Entity",
      name: "Coin",
      fileBase: "cog2_",
      fileExtension: "png",
      width: "1",
      height: "1",
      centerX: "0.45",
      delay: "0.04",
      frames: 28,
    },
    {
      type: "Entity",
      name: "Wrecker",
      fileBase: "covid_ball_",
      fileExtension: "png",
      width: "0.95",
      height: "0.95",
      centerX: "0.49",
      delay: "0.045",
      frames: 1,
    },
    {
      type: "Texture",
      name: "dirt",
      file: "dirt.jpg",
    },
    {
      type: "Texture",
      name: "sky",
      file: "sky.jpg",
    },
    { type: "Texture", flag: true, name: "us", file: "us.png" },
    { type: "Texture", flag: true, name: "india", file: "india.png" },
    { type: "Texture", flag: true, name: "brazil", file: "brazil.png" },
    { type: "Texture", flag: true, name: "russia", file: "russia.png" },
    { type: "Texture", flag: true, name: "argentina", file: "argentina.png" },
    { type: "Texture", flag: true, name: "spain", file: "spain.png" },
    { type: "Texture", flag: true, name: "colombia", file: "colombia.png" },
    { type: "Texture", flag: true, name: "france", file: "france.png" },
    { type: "Texture", flag: true, name: "peru", file: "peru.png" },
    { type: "Texture", flag: true, name: "mexico", file: "mexico.png" },
    {
      type: "Texture",
      flag: true,
      name: "united-kingdom",
      file: "united-kingdom.png",
    },
    {
      type: "Texture",
      flag: true,
      name: "south-africa",
      file: "south-africa.png",
    },
    { type: "Texture", flag: true, name: "iran", file: "iran.png" },
    { type: "Texture", flag: true, name: "chile", file: "chile.png" },
    { type: "Texture", flag: true, name: "iraq", file: "iraq.png" },
    { type: "Texture", flag: true, name: "italy", file: "italy.png" },
    { type: "Texture", flag: true, name: "bangladesh", file: "bangladesh.png" },
    { type: "Texture", flag: true, name: "germany", file: "germany.png" },
    { type: "Texture", flag: true, name: "indonesia", file: "indonesia.png" },
    {
      type: "Texture",
      flag: true,
      name: "philippines",
      file: "philippines.png",
    },
    { type: "Texture", flag: true, name: "turkey", file: "turkey.png" },
    {
      type: "Texture",
      flag: true,
      name: "saudi-arabia",
      file: "saudi-arabia.png",
    },
    { type: "Texture", flag: true, name: "pakistan", file: "pakistan.png" },
    { type: "Texture", flag: true, name: "israel", file: "israel.png" },
    { type: "Texture", flag: true, name: "ukraine", file: "ukraine.png" },
    {
      type: "Texture",
      flag: true,
      name: "netherlands",
      file: "netherlands.png",
    },
    { type: "Texture", flag: true, name: "belgium", file: "belgium.png" },
    { type: "Texture", flag: true, name: "canada", file: "canada.png" },
    { type: "Texture", flag: true, name: "romania", file: "romania.png" },
    { type: "Texture", flag: true, name: "poland", file: "poland.png" },
    {
      type: "Texture",
      flag: true,
      name: "czech-republic",
      file: "czech-republic.png",
    },
    { type: "Texture", flag: true, name: "morocco", file: "morocco.png" },
    { type: "Texture", flag: true, name: "ecuador", file: "ecuador.png" },
    { type: "Texture", flag: true, name: "bolivia", file: "bolivia.png" },
    { type: "Texture", flag: true, name: "nepal", file: "nepal.png" },
    { type: "Texture", flag: true, name: "qatar", file: "qatar.png" },
    { type: "Texture", flag: true, name: "panama", file: "panama.png" },
    {
      type: "Texture",
      flag: true,
      name: "dominican-republic",
      file: "dominican-republic.png",
    },
    { type: "Texture", flag: true, name: "kuwait", file: "kuwait.png" },
    {
      type: "Texture",
      flag: true,
      name: "united-arab-emirates",
      file: "united-arab-emirates.png",
    },
    { type: "Texture", flag: true, name: "oman", file: "oman.png" },
    { type: "Texture", flag: true, name: "kazakhstan", file: "kazakhstan.png" },
    { type: "Texture", flag: true, name: "egypt", file: "egypt.png" },
    { type: "Texture", flag: true, name: "sweden", file: "sweden.png" },
    { type: "Texture", flag: true, name: "guatemala", file: "guatemala.png" },
    { type: "Texture", flag: true, name: "portugal", file: "portugal.png" },
    { type: "Texture", flag: true, name: "costa-rica", file: "costa-rica.png" },
    { type: "Texture", flag: true, name: "japan", file: "japan.png" },
    { type: "Texture", flag: true, name: "ethiopia", file: "ethiopia.png" },
    { type: "Texture", flag: true, name: "belarus", file: "belarus.png" },
    { type: "Texture", flag: true, name: "honduras", file: "honduras.png" },
    { type: "Texture", flag: true, name: "venezuela", file: "venezuela.png" },
    { type: "Texture", flag: true, name: "china", file: "china.png" },
  ],
};

var VALID_COUNTRIES = [];
for (var i = 0; i < THEME_JSON.sprites.length; i++) {
  if (THEME_JSON.sprites[i].flag) {
    VALID_COUNTRIES.push(THEME_JSON.sprites[i].name);
  }
}
